/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package msc;

/**
 *
 * @author OSL
 */
public class adminInsert extends javax.swing.JFrame {

    /**
     * Creates new form adminInsert
     */
    connect c = new connect();
    public adminInsert() {
        initComponents();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        brands = new javax.swing.JPanel();
        lbid = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        lbname = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        insertBrands = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        viewBrands = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        models = new javax.swing.JPanel();
        lbid1 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        lbname1 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        insertBrands1 = new javax.swing.JButton();
        lbid2 = new javax.swing.JLabel();
        bid1 = new javax.swing.JTextField();
        lbError1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(320, 10, 70, 20);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        brands.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        brands.setLayout(null);

        lbid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbid.setForeground(new java.awt.Color(255, 255, 255));
        lbid.setText("Brand ID");
        brands.add(lbid);
        lbid.setBounds(70, 80, 110, 20);
        brands.add(bid);
        bid.setBounds(190, 80, 130, 26);

        lbname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbname.setForeground(new java.awt.Color(255, 255, 255));
        lbname.setText("Brand Name");
        brands.add(lbname);
        lbname.setBounds(70, 110, 110, 20);
        brands.add(bname);
        bname.setBounds(190, 110, 130, 26);

        insertBrands.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertBrands.setText("Insert");
        insertBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBrandsActionPerformed(evt);
            }
        });
        brands.add(insertBrands);
        insertBrands.setBounds(70, 140, 250, 29);

        lbError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbError.setForeground(new java.awt.Color(255, 255, 255));
        brands.add(lbError);
        lbError.setBounds(90, 220, 190, 20);

        viewBrands.setText("View brands");
        viewBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBrandsActionPerformed(evt);
            }
        });
        brands.add(viewBrands);
        viewBrands.setBounds(267, 220, 110, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/msc.png"))); // NOI18N
        brands.add(jLabel1);
        jLabel1.setBounds(0, -110, 620, 530);

        jTabbedPane1.addTab("Brands", null, brands, "add brands");

        models.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        models.setLayout(null);

        lbid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbid1.setForeground(new java.awt.Color(255, 255, 255));
        lbid1.setText("Model ID");
        models.add(lbid1);
        lbid1.setBounds(60, 60, 140, 20);
        models.add(mid);
        mid.setBounds(210, 60, 130, 26);

        lbname1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbname1.setForeground(new java.awt.Color(255, 255, 255));
        lbname1.setText("Model Name");
        models.add(lbname1);
        lbname1.setBounds(60, 90, 140, 20);
        models.add(mname);
        mname.setBounds(210, 90, 130, 26);

        insertBrands1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertBrands1.setText("Insert");
        insertBrands1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBrands1ActionPerformed(evt);
            }
        });
        models.add(insertBrands1);
        insertBrands1.setBounds(70, 160, 250, 29);

        lbid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbid2.setForeground(new java.awt.Color(255, 255, 255));
        lbid2.setText("Brand ID");
        models.add(lbid2);
        lbid2.setBounds(60, 120, 140, 20);
        models.add(bid1);
        bid1.setBounds(210, 120, 130, 26);

        lbError1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbError1.setForeground(new java.awt.Color(255, 255, 255));
        models.add(lbError1);
        lbError1.setBounds(100, 240, 190, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/msc.png"))); // NOI18N
        models.add(jLabel2);
        jLabel2.setBounds(0, -110, 620, 530);

        jTabbedPane1.addTab("Models", null, models, "add phone models");

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBrandsActionPerformed
        // TODO add your handling code here:
        //String brand_id = bid.getText();
        int bid1 = Integer.parseInt(bid.getText());
        String b_name = bname.getText();
        String sql = "INSERT INTO `msc`.`brands` VALUES ("+bid1+","+'"'+bname.getText()+'"'+")";
        c.connect(sql);
    }//GEN-LAST:event_insertBrandsActionPerformed

    private void insertBrands1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBrands1ActionPerformed
        // TODO add your handling code here:
        String model_name = mname.getText();
        int b_id1 = Integer.parseInt(bid1.getText());
        int m_id = Integer.parseInt(mid.getText());
        //int wp1 = Integer.parseInt(wp.getText());
        
        String sql = "INSERT INTO `msc`.`models`(model_id,model_name,brand_id) VALUES ("+m_id+","+'"'+model_name+'"'+","+'"'+b_id1+'"'+");";
        c.connect(sql);
    }//GEN-LAST:event_insertBrands1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        //close();
        adminLogin logoff = new adminLogin();
        setVisible(false);
        logoff.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void viewBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBrandsActionPerformed
        // TODO add your handling code here:
        String sql = "select brands,models from counting;";
        displaydata d = new displaydata();
        d.actionPerformed4(evt, sql);
    }//GEN-LAST:event_viewBrandsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminInsert().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bid1;
    private javax.swing.JTextField bname;
    private javax.swing.JPanel brands;
    private javax.swing.JButton insertBrands;
    private javax.swing.JButton insertBrands1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbError1;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbid1;
    private javax.swing.JLabel lbid2;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbname1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField mname;
    private javax.swing.JPanel models;
    private javax.swing.JButton viewBrands;
    // End of variables declaration//GEN-END:variables
}
