/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package msc;

/**
 *
 * @author OSL
 */
public  class adminLogin extends javax.swing.JFrame {

    /**
     * Creates new form adminLogin
     */
    public adminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbadminpassword = new javax.swing.JLabel();
        lbadminusername = new javax.swing.JLabel();
        adminPasswordField = new javax.swing.JPasswordField();
        adminusername = new javax.swing.JTextField();
        adminsubmit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        lbadminLogin = new javax.swing.JLabel();
        lbadminError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mobile service center");
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        lbadminpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbadminpassword.setForeground(new java.awt.Color(255, 255, 255));
        lbadminpassword.setText("Password");
        getContentPane().add(lbadminpassword);
        lbadminpassword.setBounds(90, 140, 90, 20);

        lbadminusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbadminusername.setForeground(new java.awt.Color(255, 255, 255));
        lbadminusername.setText("Username");
        getContentPane().add(lbadminusername);
        lbadminusername.setBounds(90, 110, 90, 20);
        getContentPane().add(adminPasswordField);
        adminPasswordField.setBounds(190, 140, 90, 26);
        getContentPane().add(adminusername);
        adminusername.setBounds(190, 110, 90, 26);

        adminsubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminsubmit.setText("Submit");
        adminsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(adminsubmit);
        adminsubmit.setBounds(190, 170, 90, 29);

        back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(280, 260, 110, 29);

        lbadminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbadminLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbadminLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbadminLogin.setText("Admin Login");
        getContentPane().add(lbadminLogin);
        lbadminLogin.setBounds(0, 30, 400, 30);

        lbadminError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbadminError.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbadminError);
        lbadminError.setBounds(14, 210, 370, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/msc.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -110, 620, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsubmitActionPerformed
        // TODO add your handling code here:
                String adminuser = adminusername.getText();
                String adminpass = adminPasswordField.getText();
                if(adminpass.contains("12345") &&  adminuser.contains("admin")){
                    
                    lbadminError.setText(null);
                    adminInsert adminInsert = new adminInsert(); 
                    setVisible(false);
                    adminInsert.setVisible(true);
                    
                }
                else
                {
                    lbadminError.setText("Invald username/password");
                }
    }//GEN-LAST:event_adminsubmitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        //close();
                Login1 back = new Login1();
                setVisible(false);
                back.setVisible(true);
                
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JButton adminsubmit;
    private javax.swing.JTextField adminusername;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbadminError;
    private javax.swing.JLabel lbadminLogin;
    private javax.swing.JLabel lbadminpassword;
    private javax.swing.JLabel lbadminusername;
    // End of variables declaration//GEN-END:variables

    private void close() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        System.exit(0);
    }
}
