/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package msc;

/**
 *
 * @author OSL
 */
public class insertRecord extends javax.swing.JFrame {

    /**
     * Creates new form insertRecord
     */
    connect c = new connect();
    public insertRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Customer = new javax.swing.JPanel();
        lcid = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        lcname = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        insertCustomer = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sRecord = new javax.swing.JPanel();
        lbsid = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        lbcname = new javax.swing.JLabel();
        cid2 = new javax.swing.JTextField();
        insertRecord = new javax.swing.JButton();
        lmid2 = new javax.swing.JLabel();
        mid2 = new javax.swing.JTextField();
        complaint = new javax.swing.JTextField();
        lbcomplaint = new javax.swing.JLabel();
        lbError1 = new javax.swing.JLabel();
        lbcost = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setText("back");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(330, 10, 60, 20);

        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(400, 350));

        Customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Customer.setLayout(null);

        lcid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lcid.setForeground(new java.awt.Color(255, 255, 255));
        lcid.setText("Customer ID");
        Customer.add(lcid);
        lcid.setBounds(60, 80, 140, 20);
        Customer.add(cid);
        cid.setBounds(210, 80, 130, 26);

        lcname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lcname.setForeground(new java.awt.Color(255, 255, 255));
        lcname.setText("Customer Name");
        Customer.add(lcname);
        lcname.setBounds(60, 110, 140, 20);
        Customer.add(cname);
        cname.setBounds(210, 110, 130, 26);

        insertCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertCustomer.setText("Insert");
        insertCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCustomerActionPerformed(evt);
            }
        });
        Customer.add(insertCustomer);
        insertCustomer.setBounds(70, 200, 250, 29);

        lbError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbError.setForeground(new java.awt.Color(255, 255, 255));
        Customer.add(lbError);
        lbError.setBounds(100, 240, 190, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/msc.png"))); // NOI18N
        Customer.add(jLabel1);
        jLabel1.setBounds(0, -110, 620, 530);

        jTabbedPane2.addTab("Customer", null, Customer, "add brands");

        sRecord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sRecord.setLayout(null);

        lbsid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbsid.setForeground(new java.awt.Color(255, 255, 255));
        lbsid.setText("Service ID");
        sRecord.add(lbsid);
        lbsid.setBounds(60, 50, 140, 25);
        sRecord.add(sid);
        sid.setBounds(210, 50, 130, 26);

        lbcname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbcname.setForeground(new java.awt.Color(255, 255, 255));
        lbcname.setText("Customer ID");
        sRecord.add(lbcname);
        lbcname.setBounds(60, 80, 140, 20);
        sRecord.add(cid2);
        cid2.setBounds(210, 80, 130, 26);

        insertRecord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertRecord.setText("Insert");
        insertRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRecordActionPerformed(evt);
            }
        });
        sRecord.add(insertRecord);
        insertRecord.setBounds(80, 210, 250, 29);

        lmid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lmid2.setForeground(new java.awt.Color(255, 255, 255));
        lmid2.setText("Model ID");
        sRecord.add(lmid2);
        lmid2.setBounds(60, 110, 140, 20);
        sRecord.add(mid2);
        mid2.setBounds(210, 110, 130, 26);
        sRecord.add(complaint);
        complaint.setBounds(210, 170, 130, 26);

        lbcomplaint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbcomplaint.setForeground(new java.awt.Color(255, 255, 255));
        lbcomplaint.setText("Complaint");
        sRecord.add(lbcomplaint);
        lbcomplaint.setBounds(60, 170, 140, 25);

        lbError1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbError1.setForeground(new java.awt.Color(255, 255, 255));
        sRecord.add(lbError1);
        lbError1.setBounds(100, 240, 190, 20);

        lbcost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbcost.setForeground(new java.awt.Color(255, 255, 255));
        lbcost.setText("Cost");
        sRecord.add(lbcost);
        lbcost.setBounds(60, 140, 140, 20);
        sRecord.add(cost);
        cost.setBounds(210, 140, 130, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/msc.png"))); // NOI18N
        sRecord.add(jLabel2);
        jLabel2.setBounds(0, -110, 620, 530);

        jTabbedPane2.addTab("Service Record", null, sRecord, "add phone models");

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCustomerActionPerformed
        // TODO add your handling code here:

        int cid1 = Integer.parseInt(cid.getText());
        String c_name = cname.getText();
        String sql = "INSERT INTO `msc`.`customer` VALUES ("+cid1+","+'"'+cname.getText()+'"'+")";
        c.connect(sql);
        
    }//GEN-LAST:event_insertCustomerActionPerformed

    private void insertRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRecordActionPerformed
        // TODO add your handling code here:
        int sid1 = Integer.parseInt(sid.getText());
        int cid1 = Integer.parseInt(cid2.getText());
        int mid1 = Integer.parseInt(mid2.getText());
        int cost1 = Integer.parseInt(cost.getText());
        String complaint1 = complaint.getText();
        String sql = "INSERT INTO `msc`.`record` VALUES ("+sid1+","+cid1+","+mid1+","+cost1+","+'"'+complaint1+'"'+")";
        c.connect(sql);
        
        
    }//GEN-LAST:event_insertRecordActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        //close();
        loginHome back = new loginHome();
        setVisible(false);
        back.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Customer;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cid2;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField complaint;
    private javax.swing.JTextField cost;
    private javax.swing.JButton insertCustomer;
    private javax.swing.JButton insertRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbError1;
    private javax.swing.JLabel lbcname;
    private javax.swing.JLabel lbcomplaint;
    private javax.swing.JLabel lbcost;
    private javax.swing.JLabel lbsid;
    private javax.swing.JLabel lcid;
    private javax.swing.JLabel lcname;
    private javax.swing.JLabel lmid2;
    private javax.swing.JButton logout;
    private javax.swing.JTextField mid2;
    private javax.swing.JPanel sRecord;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
