/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package msc;

/**
 *
 * @author OSL
 */
public class loginHome extends javax.swing.JFrame {

    /**
     * Creates new form loginHome
     */
    displaydata dd = new displaydata();

    public loginHome() {
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewCust = new javax.swing.JButton();
        lbadminLogin = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        insertRecords = new javax.swing.JButton();
        cid1 = new javax.swing.JTextField();
        lcid1 = new javax.swing.JLabel();
        lsid2 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        mid2 = new javax.swing.JTextField();
        lbid3 = new javax.swing.JLabel();
        viewModels = new javax.swing.JButton();
        viewRecords = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        viewCust.setText("View customers");
        viewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustActionPerformed(evt);
            }
        });
        getContentPane().add(viewCust);
        viewCust.setBounds(260, 110, 130, 29);

        lbadminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbadminLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbadminLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbadminLogin.setText("Home");
        getContentPane().add(lbadminLogin);
        lbadminLogin.setBounds(0, 30, 400, 30);

        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(300, 10, 90, 29);

        insertRecords.setText("Insert records");
        insertRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRecordsActionPerformed(evt);
            }
        });
        getContentPane().add(insertRecords);
        insertRecords.setBounds(260, 260, 130, 29);
        getContentPane().add(cid1);
        cid1.setBounds(120, 110, 130, 26);

        lcid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lcid1.setForeground(new java.awt.Color(255, 255, 255));
        lcid1.setText("Customer ID");
        getContentPane().add(lcid1);
        lcid1.setBounds(10, 110, 110, 20);

        lsid2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lsid2.setForeground(new java.awt.Color(255, 255, 255));
        lsid2.setText("Service ID");
        getContentPane().add(lsid2);
        lsid2.setBounds(10, 140, 140, 20);
        getContentPane().add(sid);
        sid.setBounds(120, 140, 130, 26);
        getContentPane().add(mid2);
        mid2.setBounds(120, 170, 130, 26);

        lbid3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbid3.setForeground(new java.awt.Color(255, 255, 255));
        lbid3.setText("Model ID");
        getContentPane().add(lbid3);
        lbid3.setBounds(10, 170, 140, 20);

        viewModels.setText("View models");
        viewModels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewModelsActionPerformed(evt);
            }
        });
        getContentPane().add(viewModels);
        viewModels.setBounds(260, 170, 130, 29);

        viewRecords.setText("View records");
        viewRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordsActionPerformed(evt);
            }
        });
        getContentPane().add(viewRecords);
        viewRecords.setBounds(260, 140, 130, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/msc.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -110, 620, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        //close();
        Login1 logoff = new Login1();
        setVisible(false);
        logoff.setVisible(true);

    }//GEN-LAST:event_logoutActionPerformed

    private void viewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustActionPerformed
        // TODO add your handling code here:
        
        int cid2=0;
        cid2 = Integer.parseInt(cid1.getText());       
        String sql = "SELECT C.CUST_ID,C.CUST_NAME,R.SID FROM CUSTOMER C, RECORD R WHERE R.CID=C.CUST_ID AND CUST_ID= "+cid2+" ;";
        dd.actionPerformed1(evt, sql);

        cid1.setText(null);
        
    }//GEN-LAST:event_viewCustActionPerformed

    private void insertRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRecordsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        insertRecord ir = new insertRecord();
        ir.setVisible(true);
    }//GEN-LAST:event_insertRecordsActionPerformed

    private void viewModelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewModelsActionPerformed
        // TODO add your handling code here:
                int mid=0;
        mid = Integer.parseInt(mid2.getText());
        String sql = "SELECT MODEL_ID,MODEL_NAME,BRAND_ID,WARRANTY_PERIOD FROM MODELS WHERE MODEL_ID="+mid+";";
        dd.actionPerformed2(evt, sql);
        mid2.setText(null);
        
    }//GEN-LAST:event_viewModelsActionPerformed

    private void viewRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordsActionPerformed
        // TODO add your handling code here:
        int sid2=0;
        sid2 = Integer.parseInt(sid.getText());
        String sql = "SELECT R.SID,C.CUST_ID,C.CUST_NAME,R.COST,R.MID,R.COMPLAINT FROM CUSTOMER C,RECORD R WHERE C.CUST_ID=R.CID AND R.SID="+sid2+";";
        dd.actionPerformed3(evt, sql);
        sid.setText(null);
    }//GEN-LAST:event_viewRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid1;
    private javax.swing.JButton insertRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbadminLogin;
    private javax.swing.JLabel lbid3;
    private javax.swing.JLabel lcid1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel lsid2;
    private javax.swing.JTextField mid2;
    private javax.swing.JTextField sid;
    private javax.swing.JButton viewCust;
    private javax.swing.JButton viewModels;
    private javax.swing.JButton viewRecords;
    // End of variables declaration//GEN-END:variables
}
